SynapseResourceGroup="synapse-ogvd-rg"
location="westeurope"
StorageAccountName="datalakeogvdlabs"
SynapseWorkspaceName="synapse-ws-ogvd-labs"
filesystem="fsogvd"
SqlUser="sqladminuser"
SqlPassword="*Optimizaciongvd"